In [3]:
# 一：特性
# 多维性
import numpy as np

# 0维
arr = np.array(5)

print(5)

print('arr的维度：',arr.ndim)

5
arr的维度： 0


In [4]:
# 1维

arr = np.array([1,2,3])

print(arr)

print('arr的维度：',arr.ndim)

[1 2 3]
arr的维度： 1


In [4]:
# 2维

arr = np.array([[1,2,3],[4,5,6]])

print(arr)

print('arr的维度：',arr.ndim)

[[1 2 3]
 [4 5 6]]
arr的维度： 2


In [5]:
# 同质性

arr = np.array([1,'hello']) # 不同的数据类型会被强制转换成相同的数据类型
print(arr)

arr = np.array([1,2.5])
print(arr)

['1' 'hello']
[1.  2.5]


In [ ]:
# 二：属性

arr = np.array(3)

print('形状：',arr.shape)
print('维度：',arr.ndim)
print('个数：',arr.size)
print('类型：',arr.dtype)
print('转置：',arr.T)



arr = np.array([1,3])

print('形状：',arr.shape)
print('维度：',arr.ndim)
print('个数：',arr.size)
print('类型：',arr.dtype)
print('转置：',arr.T)


arr = np.array([[1,3],[5,4]])

print('形状：',arr.shape)
print('维度：',arr.ndim)
print('个数：',arr.size)
print('类型：',arr.dtype)
print('转置：',arr.T)