In [6]:
"""
基础构造：适用于手动创建小规模数组或复制已有数据

np.array()
np.copy()
"""

import numpy as np
list1 = [1,2,3]
a = np.array(list1) # 是一个全新的数组
print(a)
list1[0] = 4
print(a)

a = np.copy(list1) # 是一个全新的数组
print(a)
list1[0] = 10
print(a)

[1 2 3]
[1 2 3]
[4 2 3]
[4 2 3]


In [70]:
"""
预定义形状填充：用于快速初始化固定形状的数组
"""
"全0"

a = np.zeros((3,4),dtype=float)
print("全0:",a)


"全1"
b = np.ones((3,4),dtype=float)
print("全1:",b)

"未初始化"
c = np.empty((5,4),dtype=float)
print("未初始化：",c)

"固定值"
d = np.full((3,10),3)
print("固定值:",d)


"xxxx_likes：复制其结构"
dc = np.ones_like(d)
print("ones_like:",dc)
dc = np.zeros_like(d)
print("zeros_like:",dc)
dc = np.empty_like(d)
print("empty_like:",dc)
dc = np.full_like(d,888)
print("full_like：",dc)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
未初始化： [[6.23042070e-307 2.04719289e-306 1.69120145e-306 9.34598246e-307]
 [1.69118787e-306 6.23061763e-307 1.33511290e-306 1.11258854e-306]
 [1.11261502e-306 1.42410839e-306 7.56597770e-307 6.23059726e-307]
 [1.78022342e-306 6.23058028e-307 9.34608432e-307 1.78020848e-306]
 [8.45593934e-307 9.34611148e-307 1.24610994e-306 2.22522596e-306]]
[[3 3 3 3 3 3 3 3 3 3]
 [3 3 3 3 3 3 3 3 3 3]
 [3 3 3 3 3 3 3 3 3 3]]
ones_like: [[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]
zeros_like: [[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
empty_like: [[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]
full_like： [[888 888 888 888 888 888 888 888 888 888]
 [888 888 888 888 888 888 888 888 888 888]
 [888 888 888 888 888 888 888 888 888 888]]
