In [2]:
"""
基础构造：适用于手动创建小规模数组或复制已有数据

np.array()
np.copy()
"""

import numpy as np
list1 = [1,2,3]
a = np.array(list1) # 是一个全新的数组
print(a)
list1[0] = 4
print(a)

a = np.copy(list1) # 是一个全新的数组
print(a)
list1[0] = 10
print(a)

[1 2 3]
[1 2 3]
[4 2 3]
[4 2 3]


In [70]:
"""
预定义形状填充：用于快速初始化固定形状的数组

np.zeros()
np.ones()
np.empty()
np.full()

"""
"全0"

a = np.zeros((3,4),dtype=float)
print("全0:",a)


"全1"
b = np.ones((3,4),dtype=float)
print("全1:",b)

"未初始化"
c = np.empty((5,4),dtype=float)
print("未初始化：",c)

"固定值"
d = np.full((3,10),3)
print("固定值:",d)


"xxxx_likes：复制其结构"
dc = np.ones_like(d)
print("ones_like:",dc)
dc = np.zeros_like(d)
print("zeros_like:",dc)
dc = np.empty_like(d)
print("empty_like:",dc)
dc = np.full_like(d,888)
print("full_like：",dc)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
未初始化： [[6.23042070e-307 2.04719289e-306 1.69120145e-306 9.34598246e-307]
 [1.69118787e-306 6.23061763e-307 1.33511290e-306 1.11258854e-306]
 [1.11261502e-306 1.42410839e-306 7.56597770e-307 6.23059726e-307]
 [1.78022342e-306 6.23058028e-307 9.34608432e-307 1.78020848e-306]
 [8.45593934e-307 9.34611148e-307 1.24610994e-306 2.22522596e-306]]
[[3 3 3 3 3 3 3 3 3 3]
 [3 3 3 3 3 3 3 3 3 3]
 [3 3 3 3 3 3 3 3 3 3]]
ones_like: [[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]
zeros_like: [[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
empty_like: [[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]
full_like： [[888 888 888 888 888 888 888 888 888 888]
 [888 888 888 888 888 888 888 888 888 888]
 [888 888 888 888 888 888 888 888 888 888]]


In [12]:
"""

基于数值范围生成：
np.arange()
np.linspace()
np.logspace()

"""

# 等差数列
arr = np.arange(1,51,2) # start end step。以start开始，每隔step取一个数
print(arr)

# 等间隔数列
arr = np.linspace(0,10,2) # start end num。在start和end之间取num个数，这num个数之间等间隔，包含start和end，取一个数，就是start
print(arr)

# 对数间隔数列
# start end num base。真正的start:start^base  真正的end:end^base，在真正的start和end上，分出num个数，包含start和end。
# 也可以换一种理解：log以base为底 x 为体 = start，那么x = base^start。其实我们先将start->end 等间隔分好，例如：0 5 10。然后在取base^(0 | 5 | 10)既可，就可以得出 1 32 1024
arr = np.logspace(0,10,3,base=2)
print(arr)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49]
[ 0. 10.]
[1.000e+00 3.200e+01 1.024e+03]


In [49]:
"""
特殊矩阵生成：

零矩阵：所有元素为0
单位矩阵：对角线上为1，其余为0
对角矩阵：只有对角线有非零值
对称矩阵：A = A^T

np.eye()
np.diag()
"""

# 单位矩阵
arr = np.eye(3)
print(arr)

# 对角矩阵
arr = np.diag([5,1,2,3])
print(arr)


# 转置
arr = np.array([[1],[2],[3]])
print(arr)
print(arr.T)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[5 0 0 0]
 [0 1 0 0]
 [0 0 2 0]
 [0 0 0 3]]
[[1]
 [2]
 [3]]
[[1 2 3]]


In [40]:
"""
随机数组的生成
np.random.rand()
np.random.randn()
np.random.randint()
"""

# 生成0到1之间的随机浮点数（均匀分布）
arr = np.random.rand(2,3) # 在[0,1)范围生成
print(arr)

# 生成指定范围区间的随机整数
arr = np.random.randint(2,3,(3,4)) # 在[2,3)范围生成
print(arr)

# 生成随机数列（正态分布）
arr = np.random.randn(2,3) # 在(-∞, +∞)范围生成，实际约 99.7% 在 (-3, 3) 之间，符合正态分布
print(arr)

[[0.49950563 0.41816943 0.18589371]
 [0.27188093 0.18423903 0.3931883 ]]
[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]
[[-0.55439973 -0.57135488  1.29405849]
 [ 2.35870465 -0.00800512 -0.7510743 ]]


In [47]:
# 随机种子，相当于map

# 相当于存了一个1000-结果
np.random.seed(1000)
print(np.random.randint(1,10,(3,3)))

print(np.random.randint(1,10,(3,3)))

# 直接拿1000的结果
np.random.seed(1000)
print(np.random.randint(1,10,(3,3)))

[[4 8 8]
 [1 2 1]
 [9 5 5]]
[[5 3 9]
 [3 5 3]
 [6 6 5]]
[[4 8 8]
 [1 2 1]
 [9 5 5]]


In [ ]:
"""
高级构造方法：视频暂时没讲
np.array()
np.loadtxt()
np.fromfunction()
"""