In [3]:
"""
索引/切片类型                             描述/用法

基本索引                                通过整数索引直接访问元素。索引从0开始

行/列切片                               使用冒号:切片语法选择行或列的子集

连续切片                                从起始索引到结束索引按步长切片

使用slice函数                           通过slice(start, stop, step)定义切片规则

布尔索引                                通过布尔条件筛选满足条件的元素。支持逻辑运算符 &,|
"""
import numpy as np

# 一维数组的索引约
arr = np.random.randint(1,100,20)
print(arr)

[64 19 84 41 63 40  4 73 90 50 64 20  3 28 99 38 44 68 12 37]


In [10]:
print(arr[10]) # 基本索引
print(arr[:]) # 获取全部数据
print(arr[2:5]) # 获取[start:end)的数据
print(arr[slice(2,7,1)]) # 获取[start:end)以step为步长数据
print(arr[(arr > 0) & (arr < 70)]) # 布尔索引

64
[64 19 84 41 63 40  4 73 90 50 64 20  3 28 99 38 44 68 12 37]
[84 41 63]
[84 41 63 40  4]
[64 19 41 63 40  4 50 64 20  3 28 38 44 68 12 37]


In [11]:
# 二维数组的索引与切片
arr = np.random.randint(1,100,(4,8))
print(arr)

[[33 83 45 36 56 71 48 77]
 [43 20  8 89 63 26 76 35]
 [95 63 94 29 16 35  3 11]
 [45 91 14 49 71 29 13 44]]


In [15]:
print(arr[1,3])
print(arr[1:3,2:5])# 行：[1,3) 列：[2,5) 也可以单独写一个数字，获取指定行/列也行。例如：arr[1,2:5]
print(arr[2][arr[2] > 50])

89
[[ 8 89 63]
 [94 29 16]]
[95 63 94]
