In [2]:
import numpy as np

# 算术运算
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a + b)
print(a - b)
print(a * b)
print(a / b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [4]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[4,5,6],[7,8,9],[1,2,3]])
print(a + b)
print(a - b)
print(a * b)
print(a / b)

[[ 5  7  9]
 [11 13 15]
 [ 8 10 12]]
[[-3 -3 -3]
 [-3 -3 -3]
 [ 6  6  6]]
[[ 4 10 18]
 [28 40 54]
 [ 7 16 27]]
[[0.25       0.4        0.5       ]
 [0.57142857 0.625      0.66666667]
 [7.         4.         3.        ]]


In [5]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = 3
print(a + b)
print(a - b)
print(a * b)
print(a / b)

[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[-2 -1  0]
 [ 1  2  3]
 [ 4  5  6]]
[[ 3  6  9]
 [12 15 18]
 [21 24 27]]
[[0.33333333 0.66666667 1.        ]
 [1.33333333 1.66666667 2.        ]
 [2.33333333 2.66666667 3.        ]]


In [6]:
# 广播机制
# 相同 或者 1
a = np.array([1,2,3])
b = np.array([[4],[5],[6]])

"""
扩展成：
1 2 3
1 2 3
1 2 3
和
4 5 6
4 5 6
4 5 6
"""
print(a + b)
print(a - b)
print(a * b)
print(a / b)

[[5 6 7]
 [6 7 8]
 [7 8 9]]
[[-3 -2 -1]
 [-4 -3 -2]
 [-5 -4 -3]]
[[ 4  8 12]
 [ 5 10 15]
 [ 6 12 18]]
[[0.25       0.5        0.75      ]
 [0.2        0.4        0.6       ]
 [0.16666667 0.33333333 0.5       ]]


In [7]:
# 矩阵运算

a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[4,5,6],[7,8,9],[1,2,3]])

print(a @ b)

[[ 21  27  33]
 [ 57  72  87]
 [ 93 117 141]]
