In [ ]:
"""
numpy的常用函数
"""

In [25]:
import numpy as np
# 基本数学函数

# 计算平方根

print(np.sqrt(9))
print(np.sqrt([1,4,9]))
arr = np.array([1,25,81])
print(np.sqrt(arr))


# 计算指数 e^x = y
# 默认以e为底
print(np.exp(1))
print(np.exp(0))

# 计算对数 lny=x
print(np.log(2.718281828459045))
print(np.log(1))

# 计算正序弦，余弦
print(np.sin(np.pi / 2))
print(np.cos(np.pi / 2))


# 计算绝对值
arr = np.array([1,2,-1,-3])
print(np.abs(arr))

# 计算a^b
arr = np.array([1,2,-1,-3])
print(np.power(arr,2))

# 四舍五入
# 奇进偶舍
print(np.round(3.2))
print(np.round(3.5))
print(np.round(4.5))

# 向上取整 向下取整
arr = np.array([1.2,2.3,-1.1,-3.1,-3.9])
print(np.ceil(arr))
print(np.floor(arr))

# 检测缺失值
np.isnan([1,2,3,np.nan,4])

3.0
[1. 2. 3.]
[1. 5. 9.]
2.718281828459045
1.0
1.0
0.0
1.0
6.123233995736766e-17
[1 2 1 3]
[1 4 1 9]
3.0
4.0
4.0
[ 2.  3. -1. -3. -3.]
[ 1.  2. -2. -4. -4.]


array([False, False, False,  True, False])

In [98]:
# 统计函数
np.random.seed(0)
arr = np.random.randint(1,20,3)
print(arr)

# 求和
print(np.sum(arr))

# 平均值
print(np.mean(arr))

# 计算中位数

# 奇数个：排序后中间的值
print(np.median(arr))
# 偶数个：中间两个数的平均值
print(np.median([1,2,4,4]))


# 计算标准差和方差
print(np.var(arr))
print(np.std(arr))

# 计算最大值和最小值
print(np.max(arr),np.argmax(arr))
print(np.min(arr),np.argmin(arr))

# 分位数
print(np.percentile(arr,0))
print(np.percentile(arr,100))
print(np.percentile(arr,50))
# 计算位置
# 公式: (n - 1) * p / 100
# n = 3 (数据个数)
# p = 33.3333333
# (n - 1) * p / 100 = 0.666666666
# 0.666666666在 0 ~ 1之间
# result = 1 + 0.666666666 * (13 - 1) = 8.999999992
print(np.percentile(arr,33.3333333))

# 累计和
print(np.cumsum(arr))

# 累计积
print(np.cumprod(arr))

[13 16  1]
30
10.0
13.0
3.0
42.0
6.48074069840786
16 1
1 2
1.0
16.0
13.0
8.999999992
[13 29 30]
[ 13 208 208]
[13 16  1]


In [99]:
# 比较函数

# 是否大于
print(np.greater([3,4,5,6],3))
# 是否小于
print(np.less([3,4,5,6],4))
# 是否等于
print(np.equal([3,4,5,6],4))
print(np.equal([3,4,5,6],[4,4,4,4]))
# 逻辑与
print(np.logical_and([0,4,5,6],[4,4,4,4]))
# 逻辑或
print(np.logical_or([0,4,5,6],[4,4,4,4]))
# 逻辑非
print(np.logical_not([0,4,5,6]))

# 检查元素是否至少有一个元素为True
print(np.any([0,10,0]))
# 检查元素是否全部为True
print(np.all([1,2,0]))


# 自定义条件
# np.where(条件,符合条件,不符合条件)
print(np.where(arr > 3,arr,0))
a = np.array([20,30,90,70,65])
print(np.where(a < 60,'不及格',np.where(a < 80,'良好','优秀')))
# np.select(条件，返回的结果)
print(np.select([a > 80,(a >= 60) & (a <= 80),a < 60],['优秀','良好','不及格'],default='未知'))

# 排序函数
b = np.array([21,2,1,1100])
print(np.sort(b))
print(np.argsort(b))
print(b)
print(b.sort())
print(b)

# 去重
b = np.array([21,2,2,2,1,1,1,1100])
print(np.unique(b))
print(b)

# 数组的拼接
arr1 = np.array([1,2,3])
arr2 = np.array([1,2,3])
print(np.concatenate((arr1,arr2)))


# 数组的分割
print(np.split(arr,3))
print(np.split(arr,[0,2]))

# 调整数组的形状
print(arr)
print(np.reshape(arr,(3,1)))

[False  True  True  True]
[ True False False False]
[False  True False False]
[False  True False False]
[False  True  True  True]
[ True  True  True  True]
[ True False False False]
True
False
[13 16  0]
['不及格' '不及格' '优秀' '良好' '良好']
['不及格' '不及格' '优秀' '良好' '良好']
[   1    2   21 1100]
[2 1 0 3]
[  21    2    1 1100]
None
[   1    2   21 1100]
[   1    2   21 1100]
[  21    2    2    2    1    1    1 1100]
[1 2 3 1 2 3]
[array([13], dtype=int32), array([16], dtype=int32), array([1], dtype=int32)]
[array([], dtype=int32), array([13, 16], dtype=int32), array([1], dtype=int32)]
[13 16  1]
[[13]
 [16]
 [ 1]]
